# Declare your Buildkite pipelines below
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-python-elastic-agent-client
  description: Buildkite Pipeline for python-elastic-agent-client
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/python-elastic-agent-client

spec:
  type: buildkite-pipeline
  owner: group:ingestion-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: python-elastic-agent-client
      description: A python language gRPC client for Elastic Agent's protocols
    spec:
      repository: elastic/python-elastic-agent-client
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        ingestion-team:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
