agents:
  useVault: true
  image: "python:3.10@sha256:7d04453d7b1fd7cd07386389132ff8c78c6080884c03727880e46d9b8852931b"

steps:
  - label: ":face_with_peeking_eye: Lint"
    command: "make lint"
    timeout_in_minutes: 5

  - label: ":pytest: Test"
    command: "make test"
    timeout_in_minutes: 5
