agents:
  useVault: true
  image: "python:3.10@sha256:b04494c38aa03fdc05ef1d038ef6b37ae89b5d0a39156fa880da2b5180eccb5d"

steps:
  - label: ":proto: Check proto files"
    command: ".buildkite/script/run_proto_check.sh"
    timeout_in_minutes: 5

  - wait

  - label: ":eyes: Check notice file"
    command: ".buildkite/script/run_notice_check.sh"
    timeout_in_minutes: 5

  - wait

  - label: ":face_with_peeking_eye: Lint"
    command: ".buildkite/script/run_linter_check.sh"
    timeout_in_minutes: 5

  - label: ":pytest: Test"
    command: "make test"
    timeout_in_minutes: 5
