agents:
  useVault: true
  image: "python:3.10@sha256:88687413ef82a3d5f47c3d020d24ac82285459e9870757aae7c071d49fe6de1b"

steps:
  - label: ":face_with_peeking_eye: Lint"
    command: "make lint"
    timeout_in_minutes: 5

  - label: ":pytest: Test"
    command: "make test"
    timeout_in_minutes: 5
