agents:
  useVault: true
  image: "python:3.10@sha256:fd0fa50d997eb56ce560c6e5ca6a1f5cf8fdff87572a16ac07fb1f5ca01eb608"

steps:
  - label: ":face_with_peeking_eye: Lint"
    command: "make lint"
    timeout_in_minutes: 5

  - label: ":pytest: Test"
    command: "make test"
    timeout_in_minutes: 5
