agents:
  useVault: true
  image: "python:3.10@sha256:08a49662edbfff8a296e2db2cb3235e117d1caeb09c32cba65011a2de0306440"

steps:
  - label: ":face_with_peeking_eye: Lint"
    command: "make lint"
    timeout_in_minutes: 5

  - label: ":pytest: Test"
    command: "make test"
    timeout_in_minutes: 5
