agents:
  useVault: true
  image: "python:3.10@sha256:b346d9d55e40cd6079db55370581b3bd24067acf5f1acc386107ec0843102ec9"

steps:
  - label: ":face_with_peeking_eye: Lint"
    command: "make lint"
    timeout_in_minutes: 5

  - label: ":pytest: Test"
    command: "make test"
    timeout_in_minutes: 5
