agents:
  useVault: true
  image: "python:3.10@sha256:7118d485696a1eb1105ae30e3f55e5685117a9bc0c3ffbe3830a268911e0837d"

notify:
  - if: 'build.branch =~ /^((main)|([0-9]+\.[0-9]+))\$/ && (build.state == "failed" || pipeline.started_passing)'
    slack:
      channels:
        - "#search-et-alerts"
      message: "${BUILDKITE_MESSAGE}"

steps:
  - label: ":eyes: Check notice file"
    command: ".buildkite/script/run_notice_check.sh"
    timeout_in_minutes: 5

  - wait

  - label: ":face_with_peeking_eye: Lint"
    command: ".buildkite/script/run_linter_check.sh"
    timeout_in_minutes: 5

  - wait

  - label: ":proto: Check proto files"
    command: ".buildkite/script/run_proto_check.sh"
    timeout_in_minutes: 5

  - label: ":pytest: Test"
    command: "make test"
    timeout_in_minutes: 5
