agents:
  useVault: true
  image: "python:3.10@sha256:76f22e4ce53774c1f5eb0ba145edb57b908e7aa329fee75eca69b511c1d0cd8a"

steps:
  - label: ":eyes: Check notice file"
    command: ".buildkite/script/run_notice_check.sh"
    timeout_in_minutes: 5

  - wait

  - label: ":face_with_peeking_eye: Lint"
    command: ".buildkite/script/run_linter_check.sh"
    timeout_in_minutes: 5

  - wait

  - label: ":proto: Check proto files"
    command: ".buildkite/script/run_proto_check.sh"
    timeout_in_minutes: 5

  - label: ":pytest: Test"
    command: "make test"
    timeout_in_minutes: 5
