agents:
  useVault: true
  image: "python:3.10@sha256:989f09f383a4508e837d8c02226c20e2a1111127d386f589e63ceb404f376c6d"

steps:
  - label: ":face_with_peeking_eye: Lint"
    command: "make lint"
    timeout_in_minutes: 5

  - label: ":pytest: Test"
    command: "make test"
    timeout_in_minutes: 5
