agents:
  useVault: true
  image: "python:3.10@sha256:8ad0e578e1b733f2a496b41f179175679374191a9c7ab8c63156446094a9cda8"

steps:
  - label: ":eyes: Check notice file"
    command: ".buildkite/script/run_notice_check.sh"
    timeout_in_minutes: 5

  - wait

  - label: ":face_with_peeking_eye: Lint"
    command: ".buildkite/script/run_linter_check.sh"
    timeout_in_minutes: 5

  - wait

  - label: ":proto: Check proto files"
    command: ".buildkite/script/run_proto_check.sh"
    timeout_in_minutes: 5

  - label: ":pytest: Test"
    command: "make test"
    timeout_in_minutes: 5
