#!/bin/bash 

PYTHON_PATH=/usr/share/python-elastic-agent/bin/python3
PY_AGENT_CLIENT_PATH=/usr/share/python-elastic-agent
$PYTHON_PATH $PY_AGENT_CLIENT_PATH/es_agent_client/examples/connectors/component.py
